
name: e_commerce_store_with_bloc
description: Mini e‑commerce using FakeStoreAPI

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  flutter_bloc: ^8.1.0
  equatable: ^2.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
